### ISSUE TITLE
Add orderer's BatchSize config to Fabrica config

### ISSUE THREAD

**Issue by dzikowski** [hyperledger-labs/fablo#115]
Current default config:

```
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
```
