### ISSUE TITLE
Do not use default affiliations in fabric-ca-server-config.yaml

### ISSUE THREAD

**Issue by dzikowski** [hyperledger-labs/fablo#168]
Current setup uses default `fabric-ca-server-config.yaml` file with the following affilations:
```yaml
affiliations:
   org1:
      - department1
      - department2
   org2:
      - department1
```
