### ISSUE TITLE
How to assign role

### ISSUE THREAD

**Issue by GianlucaLa** [hyperledger-labs/fablo#293]
How can i assign the three different role (admin, reader and writer) on the fablo network?
I need to specify them in the chaincode or can i just set them in config.yaml file?
Just in case i attach the config.yaml.
```yaml
################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &Orderer
      Name: OrdererMSP
      ID: OrdererMSP
      MSPDir: crypto-config/peerOrganizations/orderer.project.it/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"

      AnchorPeers:

    - &Home1
      Name: Home1MSP
      ID: Home1MSP
      MSPDir: crypto-config/peerOrganizations/home1.project.it/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Home1MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Home1MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Home1MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Home1MSP.member')"

      AnchorPeers:
          - Host: peer0.home1.project.it
            Port: 7041

          - Host: peer1.home1.project.it
            Port: 7042

    - &Home2
      Name: Home2MSP
      ID: Home2MSP
      MSPDir: crypto-config/peerOrganizations/home2.project.it/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Home2MSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('Home2MSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('Home2MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Home2MSP.member')"

      AnchorPeers:
          - Host: peer0.home2.project.it
            Port: 7061

          - Host: peer1.home2.project.it
            Port: 7062

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &Group1Defaults
    OrdererType: etcdraft
    Addresses:
        - orderer0.group1.orderer.project.it:7030
    EtcdRaft:
        Consenters:
            - Host: orderer0.group1.orderer.project.it
              Port: 7030
              ClientTLSCert: crypto-config/peerOrganizations/orderer.project.it/peers/orderer0.group1.orderer.project.it/tls/server.crt
              ServerTLSCert: crypto-config/peerOrganizations/orderer.project.it/peers/orderer0.group1.orderer.project.it/tls/server.crt

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group group1 #
    Group1Genesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orderer
                    - *Home1
                    - *Home2

    # Profile used to create channeltx for channel1 #
    Channel1:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Home1
                    - *Home2
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Home1
                - *Home2
```
